-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 17:46:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema internet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `internet` ;

-- -----------------------------------------------------
-- Schema internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `internet` DEFAULT CHARACTER SET utf8 ;
USE `internet` ;

-- -----------------------------------------------------
-- Table `internet`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internet`.`provincias` ;

CREATE TABLE IF NOT EXISTS `internet`.`provincias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet`.`ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internet`.`ciudades` ;

CREATE TABLE IF NOT EXISTS `internet`.`ciudades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `provincias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ciudades_provincias_idx` (`provincias_id` ASC) VISIBLE,
  CONSTRAINT `fk_ciudades_provincias`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `internet`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet`.`planes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internet`.`planes` ;

CREATE TABLE IF NOT EXISTS `internet`.`planes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `velocidad` INT NOT NULL,
  `precio` DECIMAL NOT NULL,
  `descuento` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internet`.`clientes` ;

CREATE TABLE IF NOT EXISTS `internet`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `ciudades_id` INT NOT NULL,
  `planes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_clientes_ciudades1_idx` (`ciudades_id` ASC) VISIBLE,
  INDEX `fk_clientes_planes1_idx` (`planes_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_ciudades1`
    FOREIGN KEY (`ciudades_id`)
    REFERENCES `internet`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_planes1`
    FOREIGN KEY (`planes_id`)
    REFERENCES `internet`.`planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
